# Generated by Django 5.1.2 on 2024-11-03 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_menu_menu_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='no_of_guests',
        ),
    ]
