# Generated by Django 5.1.2 on 2024-11-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_booking_no_of_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_of_guests',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
